### ISSUE TITLE
#13 Social Edit

### ISSUE THREAD

**Issue by ttakahashi1591** [Puppy-Playdate/puppy_playdate_fe#9]
As a visitor,
When I visit '/users/:id/socials/edit', 
I see the text "Edit An Existing Social" at the top of the page, 
text fields to fill out the following details: 
social name, date & time, location, type of social, and distance from user,
And there is a button to create a the social social called "Edit This Social!"
```

**Comment by EricBelongea** [comment]
As a CURRENT_USER (logged in with an account)
When I visit either the socials#index OR socials#show ( 
- socials#index: /users/:user_id/socials(.:format)
- socials#show: /users/:user_id/socials/:id(.:format)
I should See a button_to "Edit Social"
